/* Public club fields only; reusable server/client projection and input limits. */
(function(root){'use strict';
 const text=(v,n=300)=>String(v||'').trim().slice(0,n);
 const url=v=>{try{const u=new URL(v);return /^https?:$/.test(u.protocol)?u.href:'';}catch(_){return '';}};
 const image=(v,max=50000)=>typeof v==='string'&&v.length<=max&&/^data:image\/(jpeg|png|webp);base64,[a-zA-Z0-9+/=]+$/.test(v)?v:'';
 function clean(p){return {logo:image(p.logo),about:text(p.about,2000),website:url(p.website),facebook:url(p.facebook),mapUrl:url(p.mapUrl),achievements:text(p.achievements,2000),visitorInfo:text(p.visitorInfo,1000),amenities:text(p.amenities,500),gallery:(Array.isArray(p.gallery)?p.gallery:[]).slice(0,6).map(x=>({id:text(x.id,100),kind:x.kind==='team'?'team':'gym',caption:text(x.caption,120),photo:image(x.photo,200000)})).filter(x=>x.photo),teachers:(Array.isArray(p.teachers)?p.teachers:[]).slice(0,12).map(x=>({id:text(x.id,100),uid:/^[a-zA-Z0-9_-]{1,100}$/.test(x.uid||'')?x.uid:'',name:text(x.name,100),belt:text(x.belt,50),bio:text(x.bio,700),achievements:text(x.achievements,500),photo:image(x.photo)})).filter(x=>x.name)};}
 function project(p){return {id:p.id,n:text(p.n,150),city:text(p.city),addr:text(p.addr,500),phone:text(p.phone,80),ig:text(p.ig,100),coach:text(p.coach,150),...clean(p),schedule:(p.schedule||[]).map(s=>({d:s.d,t:s.t,n:s.n,kind:s.kind,group:s.group||(s.kind==='open'?'all':s.kind==='kids'?'kids':'adult')})),fee:p.fee||{},plans:(p.plans||[]).map(x=>({id:x.id,n:x.n,months:x.months,price:x.price,kind:x.kind,group:x.group||'adult'})),open:!!p.open,status:p.status||'approved'};}
 const api={clean,project,image,url};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.ARROW_CLUB=api;
})(typeof window==='undefined'?globalThis:window);
