'use strict';
const assert=require('node:assert/strict');const handler=require('../api/community.js');
const month=new Date().toISOString().slice(0,7);let caller='me',conflict=false,calls=[];
const docs={
 'club/test/members':{list:[{uid:'me',username:'mine',socialAllowed:true,belt:'blue',stripes:2},{uid:'peer',username:'peer',socialAllowed:true,belt:'white'},{uid:'child',username:'child',socialAllowed:false}]},
 'club/test/profile':{n:'Arrow Test'},'club/test/friends':{list:[{from:'me',to:'peer',status:'accepted'},{from:'me',to:'child',status:'accepted'}]},
 'bjj/u/me/settings':{name:'Private real name',birthDate:'2000-01-01',phone:'99112233',address:'Private address',bio:'Mat time',profileVisibility:{workouts:true,scores:true,competition:true,friends:true}},
 'bjj/u/me/log':{items:[{id:'own',d:month+'-01',min:60,type:'gi',rolls:2,audience:'public',note:'Private note'},{id:'private',d:month+'-02',min:60,type:'gi',audience:'private'},{id:'friend-workout',d:month+'-03',type:'gi',min:20,audience:'friends'}]},
 'bjj/u/me/comp':{events:[{n:'Championship',d:month+'-01',medal:'gold',privateNotes:'Secret'}]},
 ['club/test/feed/'+month]:{list:[...Array.from({length:25},(_,i)=>({id:'own'+i,uid:'me',d:month+'-01',min:60,rounds:2,subs:1,kudos:[]})),{id:'peer-post',uid:'peer',d:month+'-01',min:90},{id:'kid-post',uid:'child',d:month+'-01',min:120},{id:'friend-post',uid:'peer',audience:'friends',sealed:{cipher:'Private'}},{id:'secret',uid:'me',audience:'private',min:999}]}
};
const updated=new Map();
global.fetch=async(url,opt={})=>{const u=new URL(url);calls.push({url,opt});assert.equal(opt.headers.Authorization,'Bearer fixture');if(u.pathname==='/auth/v1/user')return response({id:caller});const path=(u.searchParams.get('path')||'').slice(3);if(opt.method==='POST'){const data=JSON.parse(opt.body);docs[data.path]=data.data;updated.set(data.path,data.updated_at);return response([]);}if(opt.method==='PATCH'){if(conflict){conflict=false;return response([]);}const data=JSON.parse(opt.body);docs[path]=data.data;updated.set(path,data.updated_at);return response([{data:data.data}]);}if(u.searchParams.get('path')?.startsWith('like.')){const prefix=u.searchParams.get('path').slice(5,-1);let rows=Object.entries(docs).filter(([p])=>p.startsWith(prefix)).map(([path,data])=>({path,data}));if(u.searchParams.has('data->participants')){const ids=JSON.parse(u.searchParams.get('data->participants').slice(3));rows=rows.filter(r=>ids.every(id=>r.data.participants?.includes(id)));}if(u.searchParams.has('order'))rows.sort((a,b)=>(b.data.d||'').localeCompare(a.data.d||'')||b.path.localeCompare(a.path));if(u.searchParams.has('or')){const match=u.searchParams.get('or').match(/data->>d.lt.([^,]+),and\(data->>d.eq.[^,]+,path.lt.([^)]*)/);assert(match);rows=rows.filter(r=>r.data.d<match[1]||(r.data.d===match[1]&&r.path<match[2]));}return response(rows.slice(0,+(u.searchParams.get('limit')||999)));}return response(docs[path]?[{data:structuredClone(docs[path]),updated_at:updated.get(path)||'2026-01-01T00:00:00Z'}]:[]);};
function response(data){return {ok:true,status:200,json:async()=>data};}
async function call(action,body,query={}){const res={code:0,setHeader(){},status(n){this.code=n;return this;},json(data){this.data=data;return this;}};await handler({method:body?'POST':'GET',url:'/api/community?'+new URLSearchParams({club:'test',action,...query}),headers:{authorization:'Bearer fixture'},body:body&&{club:'test',action,...body}},res);return res;}
(async()=>{
 let r=await call('publish',{});assert.equal(r.code,200);const p=docs['club/test/profiles/me'];assert.equal(p.workouts.length,1);assert.equal(p.competition[0].n,'Championship');for(const word of ['Private real name','2000-01-01','99112233','Private address','Private note','Secret','friend-workout'])assert(!JSON.stringify(p).includes(word),word);
 r=await call('profile',null,{uid:'me'});assert.equal(r.code,200);assert.equal(r.data.profile.club,'Arrow Test');assert.equal(r.data.profile.belt,'blue');assert.equal(r.data.profile.friends.length,1);
 r=await call('leaderboard',null,{period:'month'});assert.equal(r.code,200);assert.equal(r.data.rows.find(r=>r.uid==='me').sessions,25,'Aggregate must include beyond the initial feed page');assert.equal(r.data.rows.find(r=>r.uid==='me').min,1500);assert(!r.data.rows.some(r=>r.uid==='child'));
 docs['bjj/u/me/settings'].profileVisibility={workouts:false,scores:false,competition:false,friends:false};await call('publish',{});r=await call('profile',null,{uid:'me'});assert(!('workouts' in r.data.profile));assert(!('competition' in r.data.profile));assert(!('friends' in r.data.profile));assert.equal(r.data.profile.club,'Arrow Test');assert.equal(r.data.profile.belt,'blue');assert(!JSON.stringify(docs['club/test/profiles/me']).includes('Championship'));r=await call('leaderboard',null);assert(!r.data.rows.some(r=>r.uid==='me'));
 caller='child';assert.equal((await call('profile',null,{uid:'peer'})).code,403);assert.equal((await call('leaderboard',null)).code,403);caller='outsider';assert.equal((await call('partners',null)).code,403);caller='me';
 const session={id:'linked1',d:month+'-01',min:45,type:'gi',rolls:3,with:['peer','outsider','me','peer'],note:'Do not share',subs:[{n:'Armbar'}]};r=await call('partner-save',{session});assert.equal(r.code,200);assert.deepEqual(docs['club/test/partner-sessions/me_linked1'].participants,['peer']);assert(!JSON.stringify(docs['club/test/partner-sessions/me_linked1']).includes('Armbar'));assert(!JSON.stringify(docs['club/test/partner-sessions/me_linked1']).includes('Do not share'));
 caller='peer';r=await call('partners',null);assert.equal(r.data.items.length,1);assert.equal(r.data.items[0].min,45);caller='child';assert.equal((await call('partners',null)).data.items.length,0);caller='me';
 r=await call('remove',{id:'peer-post',d:month+'-01'});assert.equal(r.code,403);assert(docs['club/test/feed/'+month].list.some(p=>p.id==='peer-post'));
 session.with=[];await call('partner-save',{session});caller='peer';assert.equal((await call('partners',null)).data.items.length,0);caller='me';session.with=['peer'];await call('partner-save',{session});
 docs['club/test/feed/'+month].list.push({id:'linked1',uid:'me',d:month+'-01'});conflict=true;r=await call('remove',{id:'linked1',d:month+'-01'});assert.equal(r.code,200);assert(!docs['club/test/feed/'+month].list.some(p=>p.id==='linked1'));assert.deepEqual(docs['club/test/partner-sessions/me_linked1'].participants,[]);
 for(let i=0;i<35;i++)docs['club/test/partner-sessions/peer_p'+String(i).padStart(2,'0')]={id:'p'+i,owner:'peer',participants:['me'],d:month+'-01',min:60,type:'gi'};r=await call('partners',null);assert.equal(r.data.items.length,30);assert(r.data.next);const first=r.data.items.map(s=>s.id);r=await call('partners',null,{before:r.data.next});assert.equal(r.data.items.length,5);assert.equal(new Set([...first,...r.data.items.map(s=>s.id)]).size,35,'Same-day cursor must not skip partner sessions');assert.equal(r.data.next,null);assert.equal((await call('partner-save',{session:{...session,with:'peer'}})).code,400);assert.equal((await call('partner-save',{session:{...session,min:2000}})).code,400);assert.equal((await call('partners',null,{before:'bad'})).code,400);
 const res={setHeader(){},status(n){this.code=n;return this},json(){return this}};await handler({method:'GET',url:'/api/community',headers:{}},res);assert.equal(res.code,401);
 console.log('PASS community API authorization, profile redaction, complete leaderboard, reciprocal links, removal ownership and CAS');
})().catch(e=>{console.error(e);process.exitCode=1;});
